ssn/backend-dotnet/Ssn/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Ssn.Controllers
{
    public class HomeController : Controller
    {
        [Authorize(Roles = Global.ROLE_USER)]
        public ActionResult Index()
        {
            return View();
        }
    }
}

ssn/backend-dotnet/Ssn/Controllers/SpaController.cs
using Ssn.Models;
using Ssn.ViewModels;
using Ssn.ViewModels.Api;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Ssn.Controllers
{
    public class SpaController : Controller
    {
        private SsnSecurityService ssnSecurityService = new SsnSecurityService();

        private PostsManager postsManager = new PostsManager();

        private SpaInitialDataViewModel LoadData()
        {
            string loggedUser = User.Identity.Name;

            List<string> friends = ssnSecurityService.GetUsers();
            friends.Remove(User.Identity.Name);

            List<PostDto> postsDto = postsManager.GetPosts(loggedUser);
            List<Post> posts = postsDto.ConvertAll(post => new Post(post));
            return new SpaInitialDataViewModel(loggedUser, friends, posts);
        }

        [Authorize(Roles = Global.ROLE_USER)]
        public ActionResult React()
        {
            SpaInitialDataViewModel viewModel = LoadData();
            return View("~/Views/React/Index.cshtml", viewModel);
        }

        [Authorize(Roles = Global.ROLE_USER)]
        public ActionResult Angular()
        {
            SpaInitialDataViewModel viewModel = LoadData();
            return View("~/Views/Angular/Index.cshtml", viewModel);
        }
    }
}

ssn/backend-dotnet/Ssn/Views/Home/Index.cshtml
<h3 style="text-align: center">Simple Social Network</h3>
<hr />
<div style="text-align: center;">
    <a href="@Url.Action("React", "Spa")" target="_blank" class="btn btn-secondary" style="width:100px">
        <img src="~/Content/Images/react.svg" height="24" />
        <div>React</div>
    </a>
    <a href="@Url.Action("Angular", "Spa")" target="_blank" class="btn btn-secondary" style="width:100px">
        <img src="~/Content/Images/angular.svg" height="24" />
        <div>Angular</div>
    </a>
</div>
<hr />